### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by calid** [TimMikeFox/vim-java-import#2]
@TimMikeFox It seems a lot of plugin authors just go with releasing under the same license as vim itself, for example pathogen is released as:
> Copyright (c) Tim Pope. Distributed under the same terms as Vim itself. See :help license.

https://github.com/tpope/vim-pathogen#license

Also seeing MIT and a smattering of other licenses

Any preference?

**Comment by TimMikeFox** [comment]
¯\_(ツ)_/¯

Using the vim license seems like the thing to do.
